### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by smolsuryansh** [SteinerDiamine/2D-ADVENTURE#1]
I see you were trying to add README for your profile but you have added that README to your 2d game repository. Maybe you should change that

**Comment by SteinerDiamine** [comment]
> I see you were trying to add README for your profile but you have added that README to your 2d game repository. Maybe you should change that

My 2d game will gonna be vast so I have created dedicated repo for that is there anything wrong?

**Comment by smolsuryansh** [comment]
> > I see you were trying to add README for your profile but you have added that README to your 2d game repository. Maybe you should change that
> 
> My 2d game will gonna be vast so I have created dedicated repo for that is there anything wrong?

I wasn't talking about your repository, there is nothing wrong in creating a dedicated repository.

I was talking about the "README.md" file of this repository, the "README.md" file in this repository contain details about your profile and not the game itself.

To fix that, you can follow these steps:

- Create a new repository with YOUR github username.
- Add a "README.md" to your repository that you have just created with your username.
- Then add those details into that newly created "README.md" file.
